### ISSUE TITLE
レポートのWiki利用の問題点

### ISSUE THREAD

**Issue by nomuken** [mackhasegawa/lecture_image_processing#2]
レポートを書くにあたり，Wikiを利用しても良いとのことでしたがこれは不適切ではないでしょうか．
githubのWikiはコントリビューターでなくても，編集することが可能です．

本来Wikiの目的は複数人数において協力し完成させるものです．
特に，githubではOSSなアプリケーション開発に用いられるツールであるので，それを念頭に置いた利用が望まれると考えます．

**Comment by nomuken** [comment]
証明ということで，このリポジトリ内のwikiに対して `Wiki編集済み` の文章を追加しました．

**Comment by mackhasegawa** [comment]
指摘ありがとう．助かりました．よく調べていなくてすみませんでした．

**Comment by nomuken** [comment]
お忙しいところ，ご対応ありがとうございます．
もし，しっかりgithubを活用なされるのであれば，commit message等に `fixed #2` 入れるとissueとの対応も取れ，またこのissueのタイムラインにも表示され便利です．

多くのOSSでは，pull request内で使われたりすることが多いようにも思えます．
ご参考:
- [Microsoft/llvm issue](https://github.com/Microsoft/llvm/issues/37)
- [Microsoft/llvm issue](https://github.com/Microsoft/llvm/pull/39)

もし，issueからcommitを示したいのであれば，今回を例にすると
fixed by 52fae11ed8a752debf74a4286afed68e738d4cfb
なんてすると良いかもしれません．

もし，これが解決したと判断なされるのであれば，下にあるcloseを押してこのissueを閉じていただければと思います．

**Comment by mackhasegawa** [comment]
ありがとう
